### ISSUE TITLE
Can't install on osx 10.8.5

### ISSUE THREAD

**Issue by jjyr** [tmm1/rbtrace#27]
gem_make.out

```
/Users/xguox/.rvm/rubies/ruby-2.1.1/bin/ruby extconf.rb
extconf.rb:23:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
extconf.rb:23:in `<main>': Use RbConfig instead of obsolete and deprecated Config.
  -- tar zxvf msgpack-0.5.7.tar.gz
  -- ./configure --disable-dependency-tracking --disable-shared --with-pic --prefix=/Users/xguox/.rvm/gems/ruby-2.1.1@balzac/gems/rbtrace-0.4.3/ext/dst/
  -- make install
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/xguox/.rvm/rubies/ruby-2.1.1/bin/ruby
extconf.rb:6:in `sys': make install failed, please report to https://github.com/tmm1/rbtrace/issues (RuntimeError)
    from extconf.rb:40:in `block (2 levels) in <main>'
    from extconf.rb:32:in `chdir'
    from extconf.rb:32:in `block in <main>'
    from extconf.rb:28:in `chdir'
    from extconf.rb:28:in `<main>'

extconf failed, exit code 1
```

mkmf.log

```
Building msgpack
"tar zxvf msgpack-0.5.7.tar.gz"
x msgpack-0.5.7/
x msgpack-0.5.7/ac/
x msgpack-0.5.7/aclocal.m4
x msgpack-0.5.7/AUTHORS
x msgpack-0.5.7/ChangeLog
x msgpack-0.5.7/config.h.in
x msgpack-0.5.7/configure
x msgpack-0.5.7/configure.in
x msgpack-0.5.7/COPYING
x msgpack-0.5.7/INSTALL
x msgpack-0.5.7/LICENSE
x msgpack-0.5.7/Makefile.am
x msgpack-0.5.7/Makefile.in
x msgpack-0.5.7/msgpack_vc.postbuild.bat
x msgpack-0.5.7/msgpack_vc2008.sln
x msgpack-0.5.7/msgpack_vc2008.vcproj
x msgpack-0.5.7/msgpack_vc8.sln
x msgpack-0.5.7/msgpack_vc8.vcproj
x msgpack-0.5.7/NEWS
x msgpack-0.5.7/NOTICE
x msgpack-0.5.7/README
x msgpack-0.5.7/README.md
x msgpack-0.5.7/src/
x msgpack-0.5.7/test/
x msgpack-0.5.7/test/buffer.cc
x msgpack-0.5.7/test/cases.cc
x msgpack-0.5.7/test/cases.mpac
x msgpack-0.5.7/test/cases_compact.mpac
x msgpack-0.5.7/test/convert.cc
x msgpack-0.5.7/test/fixint.cc
x msgpack-0.5.7/test/fixint_c.cc
x msgpack-0.5.7/test/Makefile.am
x msgpack-0.5.7/test/Makefile.in
x msgpack-0.5.7/test/msgpack_test.cpp
x msgpack-0.5.7/test/msgpackc_test.cpp
x msgpack-0.5.7/test/object.cc
x msgpack-0.5.7/test/pack_unpack.cc
x msgpack-0.5.7/test/pack_unpack_c.cc
x msgpack-0.5.7/test/streaming.cc
x msgpack-0.5.7/test/streaming_c.cc
x msgpack-0.5.7/test/version.cc
x msgpack-0.5.7/test/zone.cc
x msgpack-0.5.7/src/gcc_atomic.cpp
x msgpack-0.5.7/src/Makefile.am
x msgpack-0.5.7/src/Makefile.in
x msgpack-0.5.7/src/msgpack/
x msgpack-0.5.7/src/msgpack.h
x msgpack-0.5.7/src/msgpack.hpp
x msgpack-0.5.7/src/object.cpp
x msgpack-0.5.7/src/objectc.c
x msgpack-0.5.7/src/unpack.c
x msgpack-0.5.7/src/version.c
x msgpack-0.5.7/src/vrefbuffer.c
x msgpack-0.5.7/src/zone.c
x msgpack-0.5.7/src/msgpack/object.h
x msgpack-0.5.7/src/msgpack/object.hpp
x msgpack-0.5.7/src/msgpack/pack.h
x msgpack-0.5.7/src/msgpack/pack.hpp
x msgpack-0.5.7/src/msgpack/pack_define.h
x msgpack-0.5.7/src/msgpack/pack_template.h
x msgpack-0.5.7/src/msgpack/sbuffer.h
x msgpack-0.5.7/src/msgpack/sbuffer.hpp
x msgpack-0.5.7/src/msgpack/sysdep.h
x msgpack-0.5.7/src/msgpack/type/
x msgpack-0.5.7/src/msgpack/type.hpp
x msgpack-0.5.7/src/msgpack/unpack.h
x msgpack-0.5.7/src/msgpack/unpack.hpp
x msgpack-0.5.7/src/msgpack/unpack_define.h
x msgpack-0.5.7/src/msgpack/unpack_template.h
x msgpack-0.5.7/src/msgpack/version.h
x msgpack-0.5.7/src/msgpack/version.h.in
x msgpack-0.5.7/src/msgpack/vrefbuffer.h
x msgpack-0.5.7/src/msgpack/vrefbuffer.hpp
x msgpack-0.5.7/src/msgpack/zbuffer.h
x msgpack-0.5.7/src/msgpack/zbuffer.hpp
x msgpack-0.5.7/src/msgpack/zone.h
x msgpack-0.5.7/src/msgpack/zone.hpp
x msgpack-0.5.7/src/msgpack/zone.hpp.erb
x msgpack-0.5.7/src/msgpack/type/bool.hpp
x msgpack-0.5.7/src/msgpack/type/define.hpp
x msgpack-0.5.7/src/msgpack/type/define.hpp.erb
x msgpack-0.5.7/src/msgpack/type/deque.hpp
x msgpack-0.5.7/src/msgpack/type/fixint.hpp
x msgpack-0.5.7/src/msgpack/type/float.hpp
x msgpack-0.5.7/src/msgpack/type/int.hpp
x msgpack-0.5.7/src/msgpack/type/list.hpp
x msgpack-0.5.7/src/msgpack/type/map.hpp
x msgpack-0.5.7/src/msgpack/type/nil.hpp
x msgpack-0.5.7/src/msgpack/type/pair.hpp
x msgpack-0.5.7/src/msgpack/type/raw.hpp
x msgpack-0.5.7/src/msgpack/type/set.hpp
x msgpack-0.5.7/src/msgpack/type/string.hpp
x msgpack-0.5.7/src/msgpack/type/tr1/
x msgpack-0.5.7/src/msgpack/type/tuple.hpp
x msgpack-0.5.7/src/msgpack/type/tuple.hpp.erb
x msgpack-0.5.7/src/msgpack/type/vector.hpp
x msgpack-0.5.7/src/msgpack/type/tr1/unordered_map.hpp
x msgpack-0.5.7/src/msgpack/type/tr1/unordered_set.hpp
x msgpack-0.5.7/ac/compile
x msgpack-0.5.7/ac/config.guess
x msgpack-0.5.7/ac/config.sub
x msgpack-0.5.7/ac/depcomp
x msgpack-0.5.7/ac/install-sh
x msgpack-0.5.7/ac/ltmain.sh
x msgpack-0.5.7/ac/missing
"./configure --disable-dependency-tracking --disable-shared --with-pic --prefix=/Users/xguox/.rvm/gems/ruby-2.1.1@balzac/gems/rbtrace-0.4.3/ext/dst/"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ac/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking if C++ API is enabled... 
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking whether gcc and cc understand -c and -o together... yes
checking build system type... x86_64-apple-darwin12.5.0
checking host system type... x86_64-apple-darwin12.5.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
checking if the linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin12.5.0 file names to x86_64-apple-darwin12.5.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin12.5.0 file names to toolchain format... func_convert_file_noop
checking for /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin12.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
checking if the linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) is GNU ld... no
checking whether the g++ linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fno-common -DPIC
checking if g++ PIC flag -fno-common -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin12.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking dependency style of gcc... none
checking if debug option is enabled... 
checking for __sync_* atomic operations... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/msgpack/version.h
config.status: creating test/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
"make install"
Making install in src
/bin/sh ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -O3 -Wall  -g -c -o unpack.lo unpack.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -O3 -Wall -g -c unpack.c  -fno-common -DPIC -o unpack.o
unpack.c:463: internal compiler error: Bus error: 10
Please submit a full bug report,
with preprocessed source if appropriate.
See <URL:http://developer.apple.com/bugreporter> for instructions.
make[1]: *** [unpack.lo] Error 1
make: *** [install-recursive] Error 1
```

**Comment by tmm1** [comment]
This is a gcc issue and can usually be resolved by either upgrading Xcode or exporting CC=clang

**Comment by epinault** [comment]
I have a similar issue with 10.10.3

I tried 

CC=clang gem install rbtrace 

but no luck so far. Maybe I should try to install Xcode .I was just trying to not use it at all...
