### ISSUE TITLE
0.4.11 build fails on Mac OS 10.15.6

### ISSUE THREAD

**Issue by npearson72** [tmm1/rbtrace#84]
I have a project that includes this version. Any way to get beyond the build error without upgrading the gem?

I ran ` CC=gcc-4.2 CFLAGS="" gem install rbtrace -v '0.4.11'` and got this output:

```
Building native extensions. This could take a while...
ERROR:  Error installing rbtrace:
        ERROR: Failed to build gem native extension.

    current directory: /Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext
/Users/nathan/.asdf/installs/ruby/2.6.5/bin/ruby -I /Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/2.6.0 -r ./siteconf20200820-66048-7hlfh.rb extconf.rb
  -- tar zxvfo msgpack-1.1.0.tar.gz
  -- env CFLAGS="" LDFLAGS="-L/usr/local/opt/openssl/lib" CC="gcc-4.2"
  -- ./configure --disable-dependency-tracking --disable-shared --with-pic --prefix=/Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext/dst/ --libdir=/Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext/dst/lib
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/nathan/.asdf/installs/ruby/2.6.5/bin/$(RUBY_BASE_NAME)
extconf.rb:6:in `sys': ./configure --disable-dependency-tracking --disable-shared --with-pic --prefix=/Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext/dst/ --libdir=/Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext/dst/lib failed, please report to https://github.com/tmm1/rbtrace/issues (RuntimeError)
        from extconf.rb:42:in `block (2 levels) in <main>'
        from extconf.rb:34:in `chdir'
        from extconf.rb:34:in `block in <main>'
        from extconf.rb:30:in `chdir'
        from extconf.rb:30:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-19/2.6.0/rbtrace-0.4.11/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11 for inspection.
Results logged to /Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-19/2.6.0/rbtrace-0.4.11/gem_make.out
```

The `mkmf.log` shows this:

```
Building msgpack
"tar zxvfo msgpack-1.1.0.tar.gz"
msgpack-1.1.0/
msgpack-1.1.0/test/
msgpack-1.1.0/test/pack_unpack.cpp
msgpack-1.1.0/test/cases.cpp
msgpack-1.1.0/test/buffer.cpp
msgpack-1.1.0/test/CMakeLists.txt
msgpack-1.1.0/test/streaming.cpp
msgpack-1.1.0/test/msgpack_vref.cpp
msgpack-1.1.0/test/object.cpp
msgpack-1.1.0/test/fixint_c.cpp
msgpack-1.1.0/test/msgpack_stream.cpp
msgpack-1.1.0/test/msgpack_container.cpp
msgpack-1.1.0/test/fixint.cpp
msgpack-1.1.0/test/reference.cpp
msgpack-1.1.0/test/msgpack_basic.cpp
msgpack-1.1.0/test/Makefile.in
msgpack-1.1.0/test/cases.mpac
msgpack-1.1.0/test/pack_unpack_c.cpp
msgpack-1.1.0/test/zone.cpp
msgpack-1.1.0/test/msgpack_cpp11.cpp
msgpack-1.1.0/test/msgpack_tuple.cpp
msgpack-1.1.0/test/object_with_zone.cpp
msgpack-1.1.0/test/convert.cpp
msgpack-1.1.0/test/cases_compact.mpac
msgpack-1.1.0/test/reference_cpp11.cpp
msgpack-1.1.0/test/Makefile.am
msgpack-1.1.0/test/iterator_cpp11.cpp
msgpack-1.1.0/test/msgpack_c.cpp
msgpack-1.1.0/test/streaming_c.cpp
msgpack-1.1.0/test/version.cpp
msgpack-1.1.0/test/limit.cpp
msgpack-1.1.0/include/
msgpack-1.1.0/include/msgpack/
msgpack-1.1.0/include/msgpack/vrefbuffer.hpp
msgpack-1.1.0/include/msgpack/fbuffer.h
msgpack-1.1.0/include/msgpack/object_fwd.hpp
msgpack-1.1.0/include/msgpack/unpack_define.h
msgpack-1.1.0/include/msgpack/detail/
msgpack-1.1.0/include/msgpack/detail/cpp03_zone.hpp
msgpack-1.1.0/include/msgpack/detail/cpp11_zone.hpp
msgpack-1.1.0/include/msgpack/version_master.h
msgpack-1.1.0/include/msgpack/zone.h
msgpack-1.1.0/include/msgpack/unpack_template.h
msgpack-1.1.0/include/msgpack/iterator.hpp
msgpack-1.1.0/include/msgpack/fbuffer.hpp
msgpack-1.1.0/include/msgpack/unpack.hpp
msgpack-1.1.0/include/msgpack/zbuffer.h
msgpack-1.1.0/include/msgpack/object.h
msgpack-1.1.0/include/msgpack/gcc_atomic.h
msgpack-1.1.0/include/msgpack/unpack.h
msgpack-1.1.0/include/msgpack/pack_define.h
msgpack-1.1.0/include/msgpack/pack.hpp
msgpack-1.1.0/include/msgpack/adaptor/
msgpack-1.1.0/include/msgpack/adaptor/set.hpp
msgpack-1.1.0/include/msgpack/adaptor/raw.hpp
msgpack-1.1.0/include/msgpack/adaptor/detail/
msgpack-1.1.0/include/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp
msgpack-1.1.0/include/msgpack/adaptor/detail/cpp11_define.hpp
msgpack-1.1.0/include/msgpack/adaptor/detail/cpp03_define.hpp
msgpack-1.1.0/include/msgpack/adaptor/detail/cpp03_msgpack_tuple.hpp
msgpack-1.1.0/include/msgpack/adaptor/fixint.hpp
msgpack-1.1.0/include/msgpack/adaptor/string.hpp
msgpack-1.1.0/include/msgpack/adaptor/vector_bool.hpp
msgpack-1.1.0/include/msgpack/adaptor/define.hpp
msgpack-1.1.0/include/msgpack/adaptor/vector.hpp
msgpack-1.1.0/include/msgpack/adaptor/cpp11/
msgpack-1.1.0/include/msgpack/adaptor/cpp11/tuple.hpp
msgpack-1.1.0/include/msgpack/adaptor/cpp11/array_char.hpp
msgpack-1.1.0/include/msgpack/adaptor/cpp11/unordered_map.hpp
msgpack-1.1.0/include/msgpack/adaptor/cpp11/forward_list.hpp
msgpack-1.1.0/include/msgpack/adaptor/cpp11/array.hpp
msgpack-1.1.0/include/msgpack/adaptor/cpp11/unordered_set.hpp
msgpack-1.1.0/include/msgpack/adaptor/vector_char.hpp
msgpack-1.1.0/include/msgpack/adaptor/list.hpp
msgpack-1.1.0/include/msgpack/adaptor/float.hpp
msgpack-1.1.0/include/msgpack/adaptor/adaptor_base.hpp
msgpack-1.1.0/include/msgpack/adaptor/int.hpp
msgpack-1.1.0/include/msgpack/adaptor/deque.hpp
msgpack-1.1.0/include/msgpack/adaptor/map.hpp
msgpack-1.1.0/include/msgpack/adaptor/check_container_size.hpp
msgpack-1.1.0/include/msgpack/adaptor/pair.hpp
msgpack-1.1.0/include/msgpack/adaptor/msgpack_tuple.hpp
msgpack-1.1.0/include/msgpack/adaptor/bool.hpp
msgpack-1.1.0/include/msgpack/adaptor/nil.hpp
msgpack-1.1.0/include/msgpack/adaptor/char_ptr.hpp
msgpack-1.1.0/include/msgpack/adaptor/tr1/
msgpack-1.1.0/include/msgpack/adaptor/tr1/unordered_map.hpp
msgpack-1.1.0/include/msgpack/adaptor/tr1/unordered_set.hpp
msgpack-1.1.0/include/msgpack/pack_template.h
msgpack-1.1.0/include/msgpack/sbuffer.h
msgpack-1.1.0/include/msgpack/sbuffer.hpp
msgpack-1.1.0/include/msgpack/type.hpp
msgpack-1.1.0/include/msgpack/zone.hpp
msgpack-1.1.0/include/msgpack/versioning.hpp
msgpack-1.1.0/include/msgpack/pack.h
msgpack-1.1.0/include/msgpack/vrefbuffer.h
msgpack-1.1.0/include/msgpack/zbuffer.hpp
msgpack-1.1.0/include/msgpack/cpp_config.hpp
msgpack-1.1.0/include/msgpack/sysdep.h
msgpack-1.1.0/include/msgpack/version.h
msgpack-1.1.0/include/msgpack/util.h
msgpack-1.1.0/include/msgpack/object.hpp
msgpack-1.1.0/include/msgpack/version.hpp
msgpack-1.1.0/include/msgpack.h
msgpack-1.1.0/include/msgpack.hpp
msgpack-1.1.0/CMakeLists.txt
msgpack-1.1.0/erb/
msgpack-1.1.0/erb/cpp03_define.hpp.erb
msgpack-1.1.0/erb/cpp03_msgpack_tuple.hpp.erb
msgpack-1.1.0/erb/cpp03_zone.hpp.erb
msgpack-1.1.0/NOTICE
msgpack-1.1.0/msgpack.pc.in
msgpack-1.1.0/AUTHORS
msgpack-1.1.0/LICENSE
msgpack-1.1.0/configure.in
msgpack-1.1.0/msgpack_vc8.sln
msgpack-1.1.0/config.h.in
msgpack-1.1.0/Makefile.in
msgpack-1.1.0/configure
msgpack-1.1.0/msgpack_vc8.vcproj
msgpack-1.1.0/README.md
msgpack-1.1.0/ac/
msgpack-1.1.0/ac/compile
msgpack-1.1.0/ac/config.sub
msgpack-1.1.0/ac/config.guess
msgpack-1.1.0/ac/missing
msgpack-1.1.0/ac/test-driver
msgpack-1.1.0/ac/ltmain.sh
msgpack-1.1.0/ac/install-sh
msgpack-1.1.0/ac/depcomp
msgpack-1.1.0/INSTALL
msgpack-1.1.0/Makefile.am
msgpack-1.1.0/aclocal.m4
msgpack-1.1.0/ChangeLog
msgpack-1.1.0/NEWS
msgpack-1.1.0/src/
msgpack-1.1.0/src/zone.c
msgpack-1.1.0/src/objectc.c
msgpack-1.1.0/src/unpack.c
msgpack-1.1.0/src/Makefile.in
msgpack-1.1.0/src/vrefbuffer.c
msgpack-1.1.0/src/version.c
msgpack-1.1.0/src/Makefile.am
msgpack-1.1.0/COPYING
msgpack-1.1.0/README
msgpack-1.1.0/msgpack_vc.postbuild.bat
"./configure --disable-dependency-tracking --disable-shared --with-pic --prefix=/Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext/dst/ --libdir=/Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext/dst/lib"
checking for a BSD-compatible install... /usr/local/opt/coreutils/libexec/gnubin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/opt/coreutils/libexec/gnubin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc-4.2
checking whether the C compiler works... no
configure: error: in `/Users/nathan/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rbtrace-0.4.11/ext/src/msgpack-1.1.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Thanks

**Comment by Angelmas** [comment]
I'm getting the same error

**Comment by npearson72** [comment]
@Angelmas I ended up downgrading my Apple command line tools version and the problem went away.

**Comment by Angelmas** [comment]
> @Angelmas I ended up downgrading my Apple command line tools version and the problem went away.

Hey thank you, What version are you using right now?

**Comment by npearson72** [comment]
I want to say it was 11.4 or 11.5. I'm not sure as this was on a different machine that I no longer have access to.

**Comment by KingsleyBawuah** [comment]
I had this problem as well and xCode version 11.4 worked!

**Comment by Kloenk** [comment]
To me it looks like updating config.guess and config.sub in msgpack should fix the issue.

**Comment by Kloenk** [comment]
Oh, no. The error I have looks identical on the first look. but Is actually a different one
